R/to-image.R
inst/htmlwidgets/vegawidget.js

See discussion at https://github.com/vegawidget/vegawidget/issues/38
A proposed refactoring of the internals of the htmlwidget to take advantage of promises.  I think this makes the code for adding listeners a lot cleaner, but also probably don't know enough about promises to fully understand the implications... @sa-lee and @ijlyttle let me know what you think!

Refactor to use promise for htmlwidget's stored view

---

CONTRIBUTING.Rmd
CONTRIBUTING.md
NEWS.md

- update contribution guide to reflect master branch becoming the reference-branch for pull-requests.
- update news

Fix #70, contribution guide

---

DESCRIPTION
inst/templates/utils-vegawidget-class.R

will fix vegawidget/altair#100

Template fix

---

CONTRIBUTING.Rmd
CONTRIBUTING.md
DESCRIPTION
NEWS.md
R/autosize.R
R/js-handler.R
R/js-listener.R
R/vegawidget.R
README.Rmd
README.md
man/add-listeners.Rd
man/vegawidget.Rd
man/vw_autosize.Rd
man/vw_handler_signal.Rd
pkgdown/_pkgdown.yml
vignettes/articles/image.Rmd
vignettes/articles/javascript.Rmd
vignettes/articles/render-vegawidget.Rmd
vignettes/vegawidget.Rmd

Documentation

---

.Rbuildignore
.gitignore
DESCRIPTION
NEWS.md
cran-comments.md
revdep/README.md
revdep/failures.md
revdep/problems.md

CRAN release 0.2.1

---

DESCRIPTION
NEWS.md
inst/shiny-demo/data-set-gapminder/server.R

In preparation for demo at UseR!

Update Shiny Gapminder app with tooltips

---

DESCRIPTION
NEWS.md
R/vega-embed.R
tests/testthat/test-vega-embed.R

Embed actions

---

DESCRIPTION
NEWS.md
R/vega-embed.R

Implement vega_embed() args properly

---

DESCRIPTION
NEWS.md
R/vegawidget.R

add unique identifier to data dependency

---

DESCRIPTION
NEWS.md
R/vegawidget.R
man/vegawidget.Rd
vignettes/articles/render-vegawidget.Rmd

Need to be clearer that the data dependency works only for local interactive sessions, not with knitr.
This makes the previous fix moot, but puts us in a good position if the underlying problem is solved.

data-dependency documentation

---

DESCRIPTION

bump version, add system requirements for image fns

---

DESCRIPTION
NEWS.md
R/utils-vegaspec.R
R/vegaspec.R
man/as_vegaspec.Rd
tests/testthat/test-vegaspec.R

add encoding argument to as_vegaspec()

---

DESCRIPTION
vignettes/vegawidget.Rmd

add example for working around dots in variable names

---

DESCRIPTION
NEWS.md
README.Rmd
README.md
cran-comments.md
revdep/README.md
revdep/cran.md
vignettes/vegawidget.Rmd

Release 0.3.2

---

.github/workflows/R-CMD-check.yaml
.github/workflows/pkgdown.yaml
DESCRIPTION

fix #163
thanks https://github.com/rstudio/plumber/pull/761/files !

update actions for quartz

---

DESCRIPTION
NEWS.md
R/utils-vegaspec.R

serialize `NA` to `null`

---

DESCRIPTION
NEWS.md
README.Rmd
README.md

update for CRAN release

---

DESCRIPTION
R/autosize.R
R/use-vegawidget.R
README.Rmd
README.md
cran-comments.md
man/use_vegawidget.Rd
man/vw_autosize.Rd
revdep/README.md
vignettes/vegawidget.Rmd

prerelease-0.4.1

---

DESCRIPTION
NEWS.md
R/vega-version.R

vectorize internal-function major()

---

DESCRIPTION
NEWS.md
R/vegawidget.R
vignettes/articles/render-vegawidget.Rmd

docs: note that promises must be converted to `vegawidget`

---

DESCRIPTION
R/to-image.R
R/to-vega.R
R/utils-javascript.R

refactor: mutualize js-file-access functions
